### ISSUE TITLE
PowerPoint 2016 Layout-Issue

### ISSUE THREAD

**Issue by Sunkua** [g21589/PPTX2HTML#2]
When converting a presentation made with PP16 the reveal.js-presentation just moves down to the right. The only thing i could do was to adjust the css but then the presentations out of older pp-versions did not work properly anymore. Do you have any idea why?
I have linked a presentation for you to replicate my issue.

[TestPresentation.pptx](https://github.com/g21589/PPTX2HTML/files/446789/TestPresentation.pptx)

**Comment by g21589** [comment]
Thanks for your feedback.
It used the default size (width and height) in reveal.js-presentation instead of the size in pptx.
I have fixed this size bug in the commit 2200062ff0ec1fefb62fe9db5a242205a904849d.
